'''English UI strings for Alien Market Bot v2.'''
EN = {
    'pick': '☀️ Hi {name}! 👋\nWelcome to the market bot — prices, smart alerts and friend invites are right here.\n\n🎬 Pick your language first:',
    'menu': '📊 <b>Main menu</b>\nEverything you need is here 👇',
    'lang_ok': '✅ English is on.',
    'prices_head': '📊 <b>Markets now</b>\n📅 {t} UTC',
    'utc_line': '🕐 {t} UTC',
    'sec_fx': '💱 <b>Currencies</b>',
    'sec_comm': '🛢 <b>Commodities & metals</b>',
    'sec_crypto': '🪙 <b>Crypto</b>',
    'gold': '🥇 Gold: <b>{v}</b> $/oz',
    'silver': '🥈 Silver: <b>{v}</b> $/oz',
    'brent': '🛢 Brent oil: <b>{v}</b> USD ({c}%)',
    'wti': '🛢 WTI oil: <b>{v}</b> USD ({c}%)',
    'plat': '⚪ Platinum: <b>{v}</b> USD ({c}%)',
    'pall': '🔘 Palladium: <b>{v}</b> USD ({c}%)',
    'copper': '🟠 Copper: <b>{v}</b> USD ({c}%)',
    'gas': '🔥 Nat gas: <b>{v}</b> USD ({c}%)',
    'comm_head': '🛢 Commodities & metals:',
    'btc': '₿ Bitcoin: <b>{v}</b> USD ({c}%)',
    'eth': '🔷 Ethereum: <b>{v}</b> USD ({c}%)',
    'fng_line': '😨 Fear & Greed: <b>{v}</b> ({c})',
    'fng_head': '😨 <b>Fear & Greed Index</b>\n\nValue: <b>{v}</b> / 100\nClass: <b>{c}</b>\n\n💡 High = greed, low = fear. Information only — not financial advice.',
    'list_head': '📋 <b>My list</b> ({n}/{limit}) {badge}',
    'list_empty': 'Your list is empty — add a symbol 👇',
    'cat_head': '✏️ Pick a category to see its symbols:',
    'add_pick': '➕ Tap a symbol to add it — or type it (e.g. BTC)',
    'add_ask': '✏️ Send a symbol, e.g.:\nBTC or dogecoin\n\nSupported: {syms}',
    'add_ok': '✅ {s} added!',
    'add_dup': 'ℹ️ {s} is already on your list.',
    'add_limit': '⛔ List is full ({n}). New features are coming soon 🎁',
    'add_bad': '❓ I do not know {s}. Send one from the supported list.',
    'del_ok': '🗑 {s} removed.',
    'set_head': '🔔 <b>Alert settings</b>\n\nStatus: {state}\nStandard threshold: 24h change ≥5% or move ≥3%\nYour level: {level}\n\n⏰ Alerts are checked every 10 minutes; you only get messaged on significant moves.',
    'mute_on': '🔇 Alerts muted.',
    'mute_off': '🔊 Alerts unmuted.',
    'vip': '🥇 VIP (sensitive thresholds: 3%/2%)',
    'std': '🥈 Standard',
    'on': '🔊 on',
    'off': '🔇 off',
    'ref_head': '📣 <b>Invite friends</b> (coming soon)',
    'ref_soon': '📣 <b>Invite friends & referrals</b>\n\n⏳ This section is temporarily off and will return soon with a better idea.\n\n💡 Until then, everything else in the bot is available.',
    'help_head': '📖 <b>Help</b>\n\nCommands:\n/start — start & pick language\n/price — live prices\n/fng — Fear & Greed\n/watchlist — my list\n/add BTC — add symbol\n/remove BTC — remove symbol\n/settings — alert settings\n/ref — friend invite (coming soon)\n/lang — switch language\n/help — this help\n\n💡 Alerts: 24h change ≥5% or move ≥3% since last alert.',
    'alert': '🚨 <b>{s}</b> big move!\n\n💰 Price: <b>{px}</b> USD\n📊 24h change: {chg}%\n⚡ Move since last alert: {mv}%\n📅 {t} UTC',
    'pump': '🚀 <b>{s}</b> is pumping!\n\n💰 Price: <b>{px}</b> USD\n📈 24h gain: <b>{chg}</b>%\n📊 24h volume: {vol}M USD\n📅 {t} UTC\n\n⚠️ Information only — not financial advice.',
    'btn_prices': '📊 Prices',
    'btn_fng': '😨 Fear & Greed',
    'btn_list': '📋 My list',
    'btn_add': '➕ Add',
    'btn_cat_crypto': '🪙 Crypto',
    'btn_cat_comm': '🛢 Commodities & metals',
    'btn_cat_fx': '💱 Currencies',
    'btn_set': '🔔 Settings',
    'btn_ref': '📣 Invite (soon)',
    'btn_help': '📖 Help',
    'btn_lang': '🌐 Language',
    'btn_back': '🔙 Menu',
    'btn_refresh': '🔄 Refresh',
    'btn_share': '📤 Share',
    'btn_mute': '🔇 Mute',
    'btn_unmute': '🔊 Unmute',
    'btn_channel': '📢 Market channel',
    'hint': 'Use the buttons below 👇 or type /help.',
    'welcome': '📊 <b>Markets, right now</b> 👇',
}
