"""Bilingual string tables for Alienpanelsbot v2."""
T = {
 'fa': {
  'lang_pick': '<b>زبانت رو انتخاب کن</b>\nChoose your language 👇',
  'lang_ok': '✅ زبان فارسی ثبت شد.',
  'menu': '<b>منوی اصلی ⚙️</b>\nاز گزینه‌های زیر بزن:',
  'b_prices': '📊 قیمت‌ها', 'b_watch': '👁 واچ‌لیست من', 'b_add': '➕ افزودن', 'b_del': '🗑 حذف',
  'b_alerts': '🔔 هشدارها', 'b_set': '⚙️ تنظیمات', 'b_ref': '🔗 دعوت دوستان', 'b_help': '❓ راهنما',
  'b_back': '◀️ بازگشت', 'b_lang': '🌐 زبان', 'b_mute_on': '🔇 بی‌صدا', 'b_mute_off': '🔊 بلند',
  'b_on': 'روشن', 'b_off': 'خاموش',
  'prices_t': '<b>📊 قیمت‌های لحظه‌ای</b>',
  'watch_t': '<b>👁 واچ‌لیست من</b>\n',
  'watch_empty': 'هنوز چیزی اضافه نکردی.\nدکمه «➕ افزودن» رو بزن.',
  'ask_sym': '✏️ نماد رو بفرست (مثلاً BTC یا ETH):',
  'added': '✅ {s} اضافه شد — از این به بعد هشدار می‌گیری.',
  'dup': '⚠️ {s} قبلاً توی لیستته.',
  'bad_sym': '❌ نماد نامعتبره.\nپشتیبانی: BTC, ETH, SOL, BNB, XRP, ADA, DOGE, AVAX, LINK, DOT, ARB, OP',
  'limit': '🔒 سقف واچ‌لیست رایگان ۱۰ تاست.\nبا دعوت دوستانت VIP بگیر تا ۵۰ تا بشه.',
  'removed': '🗑 {s} حذف شد.',
  'no_wl_item': 'چیزی برای حذف نیست.',
  'alerts_t': '<b>🔔 هشدارهای قیمتی</b>\nوضعیت: {st}\nحساسیت: {sn}\n\nیکی رو بزن:',
  's_on': 'روشن ✅', 's_off': 'خاموش ❌', 's_muted': 'بی‌صدا 🔇',
  's_relax': 'آرام ۵٪', 's_normal': 'معمولی ۳٪', 's_high': 'تیز ۱٫۵٪',
  'sens_set': '🔔 حساسیت روی {sn} تنظیم شد.',
  'vip_only': '👑 حساسیت تیز فقط برای VIP — با دعوت دوستانت فعالش کن.',
  'set_t': '<b>⚙️ تنظیمات</b>\nزبان: {lg}\nاعلان شخصی: {mt}\nVIP: {vp}',
  'lg_fa': 'فارسی', 'lg_en': 'انگلیسی',
  'vp_on': 'فعال تا {d}', 'vp_no': 'نداری — دعوت کن، هر دو ۷ روز VIP',
  'ref_t': '<b>🔗 دعوت دوستان</b>\n\nلینک اختصاصی تو:\n<code>{link}</code>\n\n🎁 هر دو طرف ۷ روز VIP هدیه می‌گیرید:\n• حساسیت تیز ۱٫۵٪\n• واچ‌لیست تا ۵۰ رمزارز\n\n👥 دعوت‌شده‌ها: {n}',
  'help_t': '<b>❓ راهنما</b>\n\n📊 قیمت‌ها — لحظه‌ای با تغییر ۲۴ ساعته\n👁 واچ‌لیست — نماد دلخواه + هشدار شخصی\n🔔 هشدارها — حساسیت دلخواه\n🔗 دعوت — لینک بفرست، هر دو VIP شید\n\n🔒 حریم خصوصی: اطلاعاتت فقط روی همین ربات ذخیره می‌شه.\nهشدارها خودکارن و توصیه خرید/فروش نیستن.',
  'nudge': 'از منوی دکمه‌ای استفاده کن 👇',
  'nope': 'این نماد توی لیستت نیست.',
  'muted_on': '🔇 اعلان‌های شخصی قطع شد.',
  'muted_off': '🔊 اعلان‌های شخصی روشن شد.',
  'alert_msg': '🔔 <b>هشدار {s}</b>\n{p} ({c}٪ در ۲۴ ساعت اخیر)',
  'ch_alert': '🔔 <b>تغییر مهم {s}</b>\n{p} ({c}٪ ۲۴ ساعت)',
  'ref_welcome': '🎁 دعوتت جواب داد — هر دو ۷ روز VIP فعال شد!',
  'ref_got': '🎁 کسی با لینک تو اومد — ۷ روز VIP بهت اضافه شد.',
  'vip_no': '—',
  'added_ch': '👁 واچ‌لیست کانال: {s} اضافه شد ({n} نماد)',
  'removed_ch': '👁 واچ‌لیست کانال: {s} حذف شد ({n} نماد)',
  'no_arg': 'نماد رو بنویس، مثلاً /add BTC',
  'wl_head_cmd': '<b>👁 واچ‌لیست کانال</b>',
 },
 'en': {
  'lang_pick': '<b>Choose your language</b>\nزبانت رو انتخاب کن 👇',
  'lang_ok': '✅ English selected.',
  'menu': '<b>Main menu ⚙️</b>\nTap an option:',
  'b_prices': '📊 Prices', 'b_watch': '👁 My Watchlist', 'b_add': '➕ Add', 'b_del': '🗑 Remove',
  'b_alerts': '🔔 Alerts', 'b_set': '⚙️ Settings', 'b_ref': '🔗 Invite friends', 'b_help': '❓ Help',
  'b_back': '◀️ Back', 'b_lang': '🌐 Language', 'b_mute_on': '🔇 Mute', 'b_mute_off': '🔊 Unmute',
  'b_on': 'On', 'b_off': 'Off',
  'prices_t': '<b>📊 Live prices</b>',
  'watch_t': '<b>👁 My watchlist</b>\n',
  'watch_empty': 'Nothing here yet.\nTap the Add button 👇',
  'ask_sym': '✏️ Send a symbol (e.g. BTC or ETH):',
  'added': '✅ {s} added — alerts are on for it.',
  'dup': '⚠️ {s} is already on your list.',
  'bad_sym': '❌ Unknown symbol.\nSupported: BTC, ETH, SOL, BNB, XRP, ADA, DOGE, AVAX, LINK, DOT, ARB, OP',
  'limit': '🔒 Free list is capped at 10.\nInvite friends for VIP (up to 50).',
  'removed': '🗑 {s} removed.',
  'no_wl_item': 'Nothing to remove.',
  'alerts_t': '<b>🔔 Price alerts</b>\nStatus: {st}\nSensitivity: {sn}\n\nTap one:',
  's_on': 'On ✅', 's_off': 'Off ❌', 's_muted': 'Muted 🔇',
  's_relax': 'Relaxed 5%', 's_normal': 'Normal 3%', 's_high': 'Sharp 1.5%',
  'sens_set': '🔔 Sensitivity set to {sn}.',
  'vip_only': '👑 Sharp sensitivity is VIP — invite friends to unlock.',
  'set_t': '<b>⚙️ Settings</b>\nLanguage: {lg}\nAlerts: {mt}\nVIP: {vp}',
  'lg_fa': 'Persian', 'lg_en': 'English',
  'vp_on': 'active until {d}', 'vp_no': 'none — invite friends, both get 7 days VIP',
  'ref_t': '<b>🔗 Invite friends</b>\n\nYour link:\n<code>{link}</code>\n\n🎁 You both get 7 days VIP:\n• Sharp 1.5% alerts\n• Watchlist up to 50 coins\n\n👥 Invited: {n}',
  'help_t': '<b>❓ Help</b>\n\n📊 Prices — live with 24h change\n👁 Watchlist — your coins + personal alerts\n🔔 Alerts — pick sensitivity\n🔗 Invite — share link, both get VIP\n\n🔒 Privacy: your data stays on this bot only.\nAlerts are automatic, not financial advice.',
  'nudge': 'Use the menu buttons 👇',
  'nope': 'That symbol is not on your list.',
  'muted_on': '🔇 Personal alerts muted.',
  'muted_off': '🔊 Personal alerts unmuted.',
  'alert_msg': '🔔 <b>Alert {s}</b>\n{p} ({c}% in 24h)',
  'ch_alert': '🔔 <b>Big move: {s}</b>\n{p} ({c}% 24h)',
  'ref_welcome': '🎁 Invite accepted — both of you now have 7 days VIP!',
  'ref_got': '🎁 Someone joined with your link — 7 days VIP added.',
  'vip_no': '—',
  'added_ch': '👁 Channel watchlist: {s} added ({n} symbols)',
  'removed_ch': '👁 Channel watchlist: {s} removed ({n} symbols)',
  'no_arg': 'Add a symbol, e.g. /add BTC',
  'wl_head_cmd': '<b>👁 Channel watchlist</b>',
 },
}